"""
Django settings for civic_flow project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from django.contrib.messages import constants as messages_constants
# Load environment variables from .env file
load_dotenv()
# BASE_DIR is the root folder of your project.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# DEBUG = False means the project is in 'Production Mode'.
# This hides detailed error pages from users and enables custom 404/500 pages.
DEBUG = os.getenv('DEBUG') == 'True'

# '*' means any domain can access this server (useful for local network testing).
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',        # The built-in admin panel
    'django.contrib.auth',         # Handles users, groups, and permissions
    'django.contrib.contenttypes',
    'django.contrib.sessions',     # Keeps users logged in across pages
    'django.contrib.messages',     # Powers the pop-up alerts/notifications
    'django.contrib.staticfiles',  # Manages CSS and JavaScript files
    'accounts',                    # Our custom app for User Profiles & Login
    'reports',                     # Our custom app for Issues & Dashboards
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Protects against form hacking
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'civic_flow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Tells Django to look in the /templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'civic_flow.wsgi.application'

# Database configuration
# Changed db to postgres
# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation: ensures users pick secure passwords.
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata' # Set to India Standard Time (+05:30)
USE_I18N = True
USE_TZ = True # Use Timezone-aware dates in the database

# Static files (CSS, JavaScript)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (Uploaded images)
# These are stored in the /media folder.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication URLs
LOGIN_REDIRECT_URL = 'dashboard'  # Where to go after logging in
LOGOUT_REDIRECT_URL = 'home'      # Where to go after logging out
LOGIN_URL = 'login'               # The name of the login page

# Email backend used for password reset during development.
# Password reset links will be printed to the console.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@civicflow.local'
EMAIL_SUBJECT_PREFIX = '[CivicFlow] '

# Message Mapping: matches Django's internal levels to Tailwind CSS colors
MESSAGE_TAGS = {
    messages_constants.DEBUG:   'info',
    messages_constants.INFO:    'info',
    messages_constants.SUCCESS: 'success',
    messages_constants.WARNING: 'warning',
    messages_constants.ERROR:   'error',
}

# Gemini AI Layer Configuration
AI_MODE = os.getenv('AI_MODE', 'demo')  # Preserved from Phase 1
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
AI_MODEL = os.getenv('AI_MODEL', 'gemini-3.8-flash')
AI_ENABLED = os.getenv('AI_ENABLED', 'True').lower() in ('true', '1')
AI_AUTO_ASSIGN = False  # Enforced suggestion-only mode
AI_CONFIDENCE_THRESHOLD = float(os.getenv('AI_CONFIDENCE_THRESHOLD', '0.75'))
AI_TIMEOUT_SECONDS = int(os.getenv('AI_TIMEOUT_SECONDS', '10'))


