# Generated by Django 6.0.2 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_add_issue_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
