# Generated by Django 5.2.16 on 2026-09-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_department_id_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAIAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_confidence', models.FloatField(blank=True, help_text='Confidence score between 0.0 and 1.0', null=True)),
                ('department_reasoning', models.TextField(blank=True, help_text='Explanation of why this department was recommended')),
                ('is_image_relevant', models.BooleanField(blank=True, help_text='Whether the uploaded image appears relevant to the issue', null=True)),
                ('image_confidence', models.FloatField(blank=True, help_text='Confidence score of relevance', null=True)),
                ('image_explanation', models.TextField(blank=True, help_text='Explanation of visual analysis')),
                ('detected_problem', models.CharField(blank=True, help_text='Problem category visually identified in the image', max_length=150)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='reports.issue')),
                ('suggested_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='reports.department')),
            ],
            options={
                'verbose_name': 'Issue AI Analysis',
                'verbose_name_plural': 'Issue AI Analyses',
            },
        ),
    ]
